#______      _____  __  __   _               _   _ _____   _____
#|  ____/\   |  __ \|  \/  | | |        /\   | \ | |  __ \ / ____|
#| |__ /  \  | |__) | \  / | | |       /  \  |  \| | |  | | (___
#|  __/ /\ \ |  _  /| |\/| | | |      / /\ \ | . ` | |  | |\___ \
#| | / ____ \| | \ \| |  | | | |____ / ____ \| |\  | |__| |____) |
#|_|/_/    \_\_|  \_\_|  |_| |______/_/    \_\_| \_|_____/|_____/


# This function will be used to determine whether blocks can be grown when there is
# no sunlight. This would ignore Minecraft's Game Mechanics of looking at light level
only-daylight-growth: false


